# Generated by Django 2.2.6 on 2019-11-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(max_length=70)),
                ('cargo_weight', models.DecimalField(decimal_places=10, max_digits=10)),
                ('cargo_move_to', models.CharField(max_length=100)),
                ('cargo_move_from', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Сarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, unique=True)),
                ('country', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('type_of_transport', models.CharField(max_length=100)),
            ],
        ),
    ]
