# Generated by Django 2.2.6 on 2019-11-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сarrier',
            new_name='Сonveyor',
        ),
    ]
