# Generated by Django 2.2.6 on 2019-11-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_auto_20191103_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_owner',
            field=models.CharField(default=0, help_text='Имя пользователя', max_length=100),
            preserve_default=False,
        ),
    ]
