# Generated by Django 2.2.6 on 2019-11-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0003_cargo_cargo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo_owner',
            field=models.CharField(max_length=100),
        ),
    ]
