# Generated by Django 2.2.6 on 2019-11-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0004_auto_20191106_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=77)),
                ('cargo', models.CharField(max_length=100)),
                ('adr_from', models.CharField(max_length=200)),
                ('adr_to', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('shipment_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('comment_field', models.TextField()),
            ],
        ),
    ]
