# Generated by Django 2.2.6 on 2019-11-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0006_auto_20191113_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo_weight',
            field=models.IntegerField(),
        ),
    ]
