# Generated by Django 2.2.6 on 2019-11-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0007_auto_20191113_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_owner', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=123)),
                ('car_type', models.CharField(max_length=100)),
                ('price_per_day', models.IntegerField()),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('data_start', models.DateTimeField()),
                ('data_end', models.DateTimeField()),
                ('selected_car', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='car_number',
            field=models.CharField(default='sss', max_length=15),
        ),
        migrations.AddField(
            model_name='transfer',
            name='driver_surname',
            field=models.CharField(default='sss', max_length=123),
        ),
        migrations.AddField(
            model_name='transfer',
            name='price',
            field=models.IntegerField(default=34),
        ),
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(default='Ok', max_length=100),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transporter_field',
            field=models.CharField(default='name', max_length=140),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='discharge_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='shipment_date',
            field=models.DateTimeField(),
        ),
    ]
