# Generated by Django 2.2.6 on 2019-12-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0008_auto_20191117_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='car_number',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='driver_surname',
            field=models.CharField(default='-', max_length=123),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(default='принято', max_length=100),
        ),
    ]
