# Generated by Django 2.2.6 on 2019-12-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0012_auto_20191208_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='data_back',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='data_rent',
        ),
    ]
