# Generated by Django 2.2.6 on 2019-12-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0013_auto_20191208_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='data_end',
            field=models.DateField(default='2019-05-22'),
        ),
        migrations.AlterField(
            model_name='service',
            name='data_start',
            field=models.DateField(default='2019-05-22'),
        ),
    ]
