# Generated by Django 2.2.6 on 2019-12-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0015_auto_20191210_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='data_end',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='data_start',
            field=models.CharField(max_length=100),
        ),
    ]
