# Generated by Django 2.2.6 on 2019-12-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0017_auto_20191210_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='data_end',
        ),
        migrations.RemoveField(
            model_name='service',
            name='data_start',
        ),
    ]
