# Generated by Django 2.2.6 on 2019-12-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0018_auto_20191210_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
