# Generated by Django 2.2.6 on 2019-12-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0020_rents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_from', models.CharField(max_length=200)),
                ('place_to', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('stops', models.IntegerField(default='2')),
            ],
        ),
    ]
