# Generated by Django 2.2.6 on 2019-12-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0022_auto_20191210_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootTransfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(max_length=110)),
                ('user_root', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=150)),
                ('crg_weight', models.CharField(max_length=7)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
            ],
        ),
    ]
